version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build: .
    volumes:
      - ./app:/var/www/html/
    depends_on:
      - db
    ports:
      - 8000:80
  db:
      image: mysql:5.7
      volumes:
        - ./dump:/docker-entrypoint-initdb.d
      ports: 
        - '3306:3306'
      expose:
        - '3306'
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_MP}
        MYSQL_DATABASE: db
        MYSQL_USER: ${USERNAME}
        MYSQL_PASSWORD: ${DB_USER_MP}
  app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '8080:80'
      environment:
        PMA_HOST: db
volumes:
    db_data: {}